name: "Mirror"

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 20 * * *'

jobs:
  run:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Manually mirror
      run: |
        mirror() {
          git clone "https://gitee.com/danwangshimoluo/jdTools"
          cd "jdTools"
          git remote add gitee "https://unless110:${{ secrets.GITEE_TOKEN }}@gitee.com/unless110/jdTools.git"
          git remote set-head origin -d
          git push gitee --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
          cd ..
        }
        mirror jaywcjlove github-rank
        mirror jaywcjlove linux-command
        mirror jaywcjlove hotkeys
         mirror jaywcjlove oscnews
        mirror jaywcjlove iNotify
        mirror jaywcjlove sgo
        mirror jaywcjlove oscnews
        mirror jaywcjlove mocker-api
        mirror jaywcjlove vim-web
        mirror jaywcjlove translater.js

